export const APP_CONFIG = {
  APP_NAME: 'Supermercado',
  COMPANY_NAME: 'Supermercado Venâncio',
  CURRENCY: 'BRL',
  LOCALE: 'pt-BR',
  TIMEZONE: 'America/Sao_Paulo',
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DELIVERY_FEE_BASE: 5.0,
  DELIVERY_FEE_PER_KM: 1.5,
  FREE_DELIVERY_THRESHOLD: 100.0,
  MIN_ORDER_VALUE: 20.0,
  LOYALTY_POINTS_PER_REAL: 1,
  MAX_DISCOUNT_PERCENTAGE: 50,
  TAX_RATE_DEFAULT: 0,
  BARCODE_FORMATS: ['ean13', 'ean8', 'code128', 'code39', 'qr'] as const,
} as const;

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ME: '/auth/me',
  },
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  CART: '/cart',
  ORDERS: '/orders',
  INVENTORY: '/inventory',
  REVIEWS: '/reviews',
  NOTIFICATIONS: '/notifications',
  LOYALTY: '/loyalty',
  COUPONS: '/coupons',
  SELLERS: '/seller',
  DELIVERY: '/delivery',
  ANALYTICS: '/analytics',
  REPORTS: '/reports',
  USERS: '/users',
  SUPPLIERS: '/suppliers',
} as const;
